### PR TITLE
BD-900:Relicense Lightning-SDK to Metrological Apache update

### PR DESCRIPTION
**Pull request by mallikarjuna54**
BD-900:Relicense Lightning-SDK to Metrological Apache update

Reason for change:Relicense Lightning-SDK to Metrological Apache
Test Procedure: Jenkin build should pass after License header changes for RDK for listed repos
BD-900:Relicense Lightning-SDK to Metrological Apache update
Risks: None

### CODE REVIEW

**Review by mhughesacn — CHANGES_REQUESTED** [review]
Hi Mallikarjuna - finally getting back to this.  You will have to fix the conflict, and also please check the header on rollup.config.js.  Otherwise all good.  Thanks.

**Comment by mhughesacn** [comment]
Hi Mallikarjuna: Not your fault but the ground has shifted underneath you and there are new files which you might as well fix as part of this header work.  They are:
    src/Colors/index.js
    src/Colors/utils.js
    src/helpers/sequence.js
I will clear the Blackduck errors when these are in.
Thanks

**Comment by mhughesacn** [comment]
Thanks Mallikarjuna.  I have completed the Id work and I am happy for this to merge.

**Comment by pradeeptakdas** [comment]
Hi @woutermeek 
Please merge this PR if you are Happy. Thanks!

**Comment by michielvandergeest** [comment]
Closing in favor of PR #219

**Pull request closed without merging**
